=== Strelts0v/Archive/Server/data/schemas/dossiers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:simpleType name="Login" >
        <xs:restriction base="xs:ID" >
            <xs:pattern value="([a-zA-Z0-9])+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Address">
        <xs:sequence>
            <xs:element name="country" type="xs:string" />
            <xs:element name="city" type="xs:string" />
            <xs:element name="street" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dossier">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="address" type="Address" />
            <xs:element name="mobile" type="xs:string" />
            <xs:element name="skype" type="xs:string" />
            <xs:element name="experience" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="login" type="Login" use="required" />
        <xs:attribute name="role" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string" >
                    <xs:enumeration value="GUEST"></xs:enumeration>
                    <xs:enumeration value="USER"></xs:enumeration>
                    <xs:enumeration value="ADMIN"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="dossiers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dossier"
                         type="dossier"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Strelts0v/Archive/Server/data/xml/dossiers.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<dossiers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/data/schemas/dossiers.xsd">
    <dossier login="gleb4477" role="ADMIN">
        <name>Gleb Streltsov</name>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Prushinskih 47</street>
        </address>
        <mobile>+375296949195</mobile>
        <skype>ka1oken_4by</skype>
        <experience>I'm a second year student of Belarussian State University of Informatics and Radioelectronics, study in faculty of Computer systems and networks. My passion is to use technology based solutions to solve real world problems and challenges! Now I'm looking for a job in close-knit team specializing in web development.</experience>
    </dossier>
    <dossier login="vi4477" role="ADMIN">
        <name>Veronika Sanko</name>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Gerasimenko 7</street>
        </address>
        <mobile>+375291239671</mobile>
        <skype>vivi_sanko</skype>
        <experience>none</experience>
    </dossier>






</dossiers>
